//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilet
    {
        public int BiletId { get; set; }
        public string FilmAdi { get; set; }
        public string KoltukNumarasi { get; set; }
        public string SalonNo { get; set; }
        public string SeansSaati { get; set; }
        public string BiletTipi { get; set; }
        public Nullable<int> Ucret { get; set; }
        public string mstAd { get; set; }
        public string mstSoyad { get; set; }
        public string mstTelefon { get; set; }
        public Nullable<System.DateTime> TarihSaat { get; set; }
    }
}
