//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int FilmId { get; set; }
        public string FilmAdi { get; set; }
        public Nullable<System.DateTime> FilmVizyonTarihi { get; set; }
        public string FilmYonetmen { get; set; }
        public string FilmOyuncu { get; set; }
        public string FilmDili { get; set; }
        public Nullable<int> FilmSuresi { get; set; }
        public string FilmTuru { get; set; }
        public byte[] FilmResmi { get; set; }
    }
}
