//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seans
    {
        public int SeansId { get; set; }
        public string SalonId { get; set; }
        public string FilmAdi { get; set; }
        public System.DateTime Tarihi { get; set; }
        public string Saati { get; set; }
        public string BitisSaati { get; set; }
    }
}
